name: pizzashop

services:
  pg:
    image: bitnami/postgresql:14.15.0
    container_name: pizzashop-pg
    ports:
    - 5433:5432
    env_file:
      - .env

#por enquanto subir sรณ o docker, depois coloco um pro node